### ISSUE TITLE
Resitance readings

### ISSUE THREAD

**Issue by zygisber** [ReservedField/evic-sdk#15]
I have Cubis atomizer, it comes with three heads, SS316 1,05 Ohm, SS316 0,56 Ohm and “Clapton” 1,56 Ohm. With SS316 coils everything looks fine, they heat in your example code and get back to normal resistance after some time while power off (I can do all temp calculations somehow correct too). However using “Clapton” looks strange. While power off, resistance value always reads as ~1,75Ohm and while firing it drops to ~1,59Ohm. How to explain such behavior and how come original firmware initially reads correct resistance (~1,56 instead of ~1,75 in our case)?

**Comment by ReservedField** [comment]
The Cubis Claptons should be Kanthal, right? So there shouldn't be no resistance change. Even if there was, res shouldn't go down but up. SDK bug, I guess.
I just posted an error table for resistances and testing voltages over at issue #14. The code has been tested a lot for subohm stuff, not really that much for higher resistances.
In the next days I'll write smarter code for resistance reading, so I'd wait for it and test again once it's stable.

**Comment by ReservedField** [comment]
Sorry, I re-read this and it's clearer now. Yes, same issue as in #14. The first test is done with 1V, which obviously doesn't work well with higher resistances. Once you fire, it is tested against the current atomizer voltage, which will be higher (unless you're firing at like half a watt for a 1,5ohm res). Higher test voltage = more precise resistance reading. Actually, my calculations predict a little less than 5% maximum error for that resistance, but your reading is +10% off.
I guess I'll double the error when writing resistance reading code :)

**Comment by ReservedField** [comment]
Could you check against the `experimental` branch (commit d66b66d)?

**Comment by ReservedField** [comment]
Since this deals with the same issue as in #14, I'm closing it. Let's continue the discussion there.
