### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by RudiBoy95** [ReservedField/evic-sdk#19]
I can't compile it on OS X already got python-evic compiled working and tested I don't know whats happening 

arm-none-eabi-as -mcpu=cortex-m4 -o src/startup/evicsdk_tag.o src/startup/evicsdk_tag.s
mkdir -p lib
arm-none-eabi-ld -r src/startup/startup.o src/startup/evicsdk_tag.o -o lib/libevicsdk_crt0.o
make: **\* No rule to make target `/nuvoton-sdk/Library/Device/Nuvoton/M451Series/Source/system_M451Series.o', needed by`libevicsdk.a'.  Stop.

**Comment by Ban3** [comment]
Your EVICSDK doesn't seem to be set correctly. Actually, I think OSX doesn't read `.bashrc` by default, so the README is incorrect.

Could you do `source ~/.bashrc` and try again?
