### ISSUE TITLE
GDDRAM cleaning & global framebuffer

### ISSUE THREAD

**Issue by ReservedField** [ReservedField/evic-sdk#2]
Right now we have two approaches to GDDRAM cleaning: in my SSD1306 driver, the GDDRAM writing code is duplicated, but no empty framebuffer is allocated (zero bytes are sent out one by one). In Ban3's SSD1327 driver, the GDDRAM writing code is not duplicated, at the cost of allocating a 1kB empty framebuffer on the stack. This code is called at the beginning of an APROM,  so there's plenty of RAM and it shouldn't be a problem (I originally wrote the code like that thinking of a RAM-deprived environment). The framebuffer is allocated by the APROM code. The original firmware uses a different strategy: the display library allocates the framebuffer, and the APROM code accesses it through drawing primitives. I think this is a superior solution, since it hides away the framebuffer from the user. Plus it would allow to refactor the GDDRAM cleaning without code duplication and without risking a stack crash (even if it's unlikely).
What do others think?

**Comment by Ban3** [comment]
> The original firmware uses a different strategy: the display library allocates the framebuffer, and the APROM code accesses it through drawing primitives. I think this is a superior solution, since it hides away the framebuffer from the user.

I agree with this one. I really didn't want to force any architectural changes with the driver, the clearing is just a placeholder for now. Write, clear, and sendcommand could easily be factored out as long as the framebuffer format is shared.

**Comment by ReservedField** [comment]
Ok, I think I'll be going with the (0,0) in the standard top-left position (with the eVic standing up). Right now (0,0) at bottom right is just awkward.
We need to save RAM, so framebuffer will encode 8 pixels per byte (no readback from the GDDRAM I'm afraid). The only thing left to decide is column- or row-major indexing. Row-major is the most widely used, but since we use 8 pixels/byte any width not a multiple of 8 will need bitmasking. This is awkward when dealing with fonts, where the height can be fixed most of the times but the width varies with non-monospaced chars. Column-major (which is the one I'm using right now) needs multiple-of-8 heights to avoid bitmasking but gives more freedom with width. Given that the vertical resolution is twice the horizontal one (screen is 64x128) I think we should go with column-major.

**Comment by ReservedField** [comment]
In the end, I only changed (0,0) to be top-left. The framebuffer is still paged. This is because the tool I'm using to generate font bitmaps (The Dot Factory) generates paged bitmaps when in column-major mode, and I'm not that good with C#, so I think changing it would be just a waste of time. I refactored the display code. I could not get the common display on + delay out of the individual inits. If I moved it to the common init it stopped working. I have no idea why, I spent a couple hours banging my head on the wall for that. So the framebuffer is cleared before init, then the driver init calls Display_Update() before setting the display on. Strangest bug ever...

**Comment by ReservedField** [comment]
I'm reopening this. At the moment non-8-aligned vertical coordinates are not supported because it's a royal pain to deal with them if the framebuffer is paged. I guess I'll have to play with the font tool to get a non-paged column-major format.

**Comment by ReservedField** [comment]
The tool allows rotation and flipping, so I'm thinking that setting it to row-major with a 90° counterclockwise rotation and flipping Y should emulate a non-paged column-major buffer. I'll try that.

**Comment by ReservedField** [comment]
Closing this as column-major framebuffer has been implemented in the new-framebuffer branch (SSD1327 left to test before merging to master).
