### ISSUE TITLE
Display_PutPixels not always working.

### ISSUE THREAD

**Issue by Emilgardis** [ReservedField/evic-sdk#23]
So I've got my code on [my dev branch](https://github.com/Emilgardis/evic-sdk/tree/13b7fbca3b077e471cd16badd015a5e60986d8d9/own-soft/atomizer)

This compiles but gives me an incorrect bitmap.
Picture:
![pic](http://imgur.com/Hlt1gfU.png)

**Comment by ReservedField** [comment]
Does it print correctly if you vary the coordinates?

**Comment by Emilgardis** [comment]
Does not work either. I also commented out every line concerning output to Display. No success.

here are the bins. (Sorry, I uploaded the wrong ones, the correct one to use in bins.zip is the unencrypted one. bins_nothingelse.zip is the correct one)

[~~bins.zip~~](https://github.com/ReservedField/evic-sdk/files/204353/bins.zip)

[bins_nothingelse.zip](https://github.com/ReservedField/evic-sdk/files/204364/bins_nothingelse.zip)

**Comment by Emilgardis** [comment]
One thing to note is that it looks exactly the same now as it did before. I'm fairly certain that it is not the fault of img-convert

**Comment by ReservedField** [comment]
Should be fixed in 306e8fc, it was indeed an issue with img-convert not padding column bits correctly. Sorry about the delay. Could you test and report back?

**Comment by Emilgardis** [comment]
Commit fixes it, works fine now!
