### ISSUE TITLE
No atomizer detected after a weak battery

### ISSUE THREAD

**Issue by Blop1759** [ReservedField/evic-sdk#25]
Hi again, 

Thanks for taking my "perhaps sometimes stupids" tests into account, but that's right this no detection could be an interesting issue in fact.

So, while testing the weak battery, with a 50% battery, inox 0.7 ohm 316L coil on a Presa 75TC (again, settings are right, shunt resistance at 100), testing at 65W in order to have a real weak battery message with the atomizer example, just after the weak battery state, I got a "NO ATOM" state.

What i'm suspecting is a not perfect test of resistance for the TC coils.

I have done some other tests and I often see a higher base resistance than what I assume to be the real one and while firing from cold, a lower resistance is often shown (not always) : from base res 0.75 to live res 0.68 for instance.
(Of course, the atomizer was plugged cold or battery inserted with cold atomizer plugged)

This could be a hint for this state just after a weak state ?

**Comment by ReservedField** [comment]
This may be because atomizer resistance is reset after error. It made sense when the only errors were SHORT and OPEN, but I didn't think about it when I added WEAK_BATT and OVER_TEMP. Could you (as a quick test, it's not a good fix) try commenting out line 324 in Atomizer.c? It's the `Atomizer_baseRes = 0` one inside the `if(Atomizer_error != OK)`, in case I messed up the line number (mobile sucks).

**Comment by Blop1759** [comment]
I'll try as soon as I'm at home, I see where this test is, That right the baseres must not be reset in those two cases.

**Comment by Blop1759** [comment]
Test done !
I haven't a weak battery available, so I've done two tests in one : weak and too hot.

With this code in the feedback loop : 

```
if(Atomizer_error != OK) {
    if (Atomizer_error == OPEN || Atomizer_error == SHORT) {
        Atomizer_baseRes = 0;
        Atomizer_tempRes = 0;
    }
    Atomizer_Control(0);
    return;
}
```

No more NO ATOM, except when my test coil finally burn out ...

I haven't seen the too hot state, went up to 55°C till my coil die.

**Comment by ReservedField** [comment]
Umm the too hot is not coil-related. It's the board temperature. 55°C seems about right. You really don't want it to shoot up to 70°C. Did you just burn a coil on purpose for this? :P

**Comment by Blop1759** [comment]
No, it's just as my available battery for the test was not discharged enough to easily get the weak state, Ihad to shoot quite hard to get it and as the coil wasn't a fresh one, it broke ;)
70° is perhaps a little high ?

**Comment by ReservedField** [comment]
70°C is the limit used in OFW, so I'm guessing it's good. Even the crappiest chips are rated up to 85°C, and power components have maximum junction temperatures in the 100-150°C range. Plus this is the heatsink temp, which won't deliver much heat to the battery. I'd say 70°C is fine.

I'll fix the bug today.

**Comment by Blop1759** [comment]
That's also right during summer a lower limitation could be a bad thing.

Perfect !
