### ISSUE TITLE
How to extract data?

### ISSUE THREAD

**Issue by mickey** [ReservedField/evic-sdk#31]
Thanks for the awesome work put into this.
I'd like to extract the data of my VIC, especially the number/time of puffs.
Any idea how to do this?
Thanks!

**Comment by ReservedField** [comment]
I don't have an OFW installed right now to check, but I looked up the offsets in my reversed binaries. Make a dump: `evic-usb dump-dataflash -o dataflash.bin`
Then open it up with your favorite hex editor and you can find what you're looking for at those offsets:

```
+0x130 | Total puff count
+0x134 | Total puff time (in 100ms units)
```

Both values are unsigned 32-bit little-endian integers. I checked against an old dump of mine and they work out.
If you want to dump them at runtime from a custom APROM, it's a little more complex. OFW dataflash is 8kB (4 2kB pages, let's number them 0-1-2-3). Read up page 2 word by word until you get `0xFFFFFFFF`, the word before that is the most recent total puff count. If you get no FF word then the last word is the most recent count. The same index is valid in page 3 to get the total puff time. Off the top of my head (didn't test nor compile):

```
uint32_t puffBaseAddr, index, word, puffCount = 0, puffTime = 0;

SYS_UnlockReg();
FMC_Open();
puffBaseAddr = FMC_ReadDataFlashBaseAddr() + FMC_FLASH_PAGE_SIZE * 2;
for(index = 0; index < FMC_FLASH_PAGE_SIZE / 4; index++) {
    word = FMC_Read(puffBaseAddr + 4 * index);
    if(word == 0xFFFFFFFF) {
        break;
    }
    puffCount = word;
}
if(index != 0) {
    puffTime = FMC_Read(puffBaseAddr + FMC_FLASH_PAGE_SIZE + 4 * (index - 1));
}
FMC_Close();
SYS_LockReg();
```

**Comment by mickey** [comment]
wow thanks a lot for the explanation :D
It works great!

<img width="1285" alt="image 2016-06-02 at 6 21 43 pm" src="https://cloud.githubusercontent.com/assets/10755/15752566/00cffa9e-28ef-11e6-8fec-ba8759adcda5.png">
