### ISSUE TITLE
evic-convert: not found

### ISSUE THREAD

**Issue by cristalcorp** [ReservedField/evic-sdk#36]
Hi,
First of all great project, thank you !

I'm using a Debian 8, i cloned your repo, followed the installation guide, downloaded http://www.nuvoton.com/opencms/resource-download.jsp?tp_GUID=SW0120140916095112 and copied the Library folder into my evic-sdk/nuvoton-sdk/ folder (which I had to create), exported the sdklocation in my bashrc file and reloaded a new terminal.

The SDK compiled perfectly though while trying to compile the helloworld example (or any other example for that matter), evic-convert seems not to be found and I get the following error :

[evic-dbg] ENC bin/dbg/evic/helloworld.bin
/bin/sh: 1: evic-convert: not found
[path_to_sdk]/evic-sdk/make/Base.mk:140: recipe for target 'bin/dbg/evic/helloworld.bin' failed
make: *** [bin/dbg/evic/helloworld.bin] Error 127

Am I forgetting something or is it a bug ?

Once again, big thanks for that project which actually helped me for choosing my e-cig ;)

**Comment by Emilgardis** [comment]
You need to install [python-evic](https://github.com/Ban3/python-evic)

**Comment by cristalcorp** [comment]
> On any OS, you also need a working python-evic install. If you experience problems with hidapi, you can flash using the official updater. The conversion utilies needed by the SDK will work anyway.

My bad I did not see that part in the tuto...

Subject closed. Thanks again.
